name: Chatterbox
main: works.chatterbox.chatterbox.Chatterbox
version: ${pluginversion}
authors: [jkcclemens, gdude2002]
description:  Simple, elegant, powerful. Minecraft chat as it was supposed to be.

reflectcommands:
- commands.impl.ChannelCommand
- commands.impl.JoinCommand
- commands.impl.LeaveCommand
- commands.impl.ChatterboxCommand
- commands.impl.formats.action.ActionCommand
- commands.impl.formats.say.SayCommand
