name: Chatterbox
main: works.chatterbox.chatterbox.Chatterbox
version: ${pluginversion}
authors: [jkcclemens, gdude2002]
description:  Simple, elegant, powerful. Minecraft chat as it was supposed to be.

commit: ${describe}

reflectcommands:
- commands.impl.ChannelCommand
- commands.impl.JoinCommand
- commands.impl.LeaveCommand
- commands.impl.ReloadCommand
- commands.impl.formats.action.ActionCommand
- commands.impl.formats.say.SayCommand
- commands.impl.messaging.MessageCommand
- commands.impl.messaging.ReplyCommand

commands:
  chatterbox:
    description: Base command
    aliases: [chat]
    usage: /<command>
